stages:
  - build
Win7-VS12-x64-subproject:
  stage: build
  script:
  - call %ENVFILESDIR%\Boost-1.64-vs12-x64.bat
  - call %ENVFILESDIR%\zeromq-4.0.4.bat
  - set PATH=%PATH%;"c:\Program Files (x86)\Git\bin"
  - set BUILD_GENERATOR=Visual Studio 12 Win64
  - set CMAKE_EXTRA_ARGS="-DWITH_NO_CONSOLE=ON"
  - pip install pyparsing
  - bash --login .gitlab-ci.sh
  tags:
  - win7
  except:
  - tags
Ubuntu-subproject:
  stage: build
  script:
  - bash .gitlab-ci.sh
  tags:
  - ubuntu
  except:
  - tags
OSX-subproject:
  stage: build
  script:
  - bash .gitlab-ci.sh
  tags:
  - osx
  except:
  - tags